/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:f340e9dd-02ac-40ba-bbb3-86ca26b27c46",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_RCRl6JGnK",
    "aws_user_pools_web_client_id": "7d4crldkhrk1k90u89cckgmbp6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://zmw7k4basndbfklxvkqsmwp3pi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "mychat558b5f05d70b4224946be66aa15a0971d57a5-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
